### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by ewelinajozwik** [thehyve/transmart-variant-store-connector#2]
[README](https://github.com/thehyve/transmart-variant-store-connector/blob/master/README.md#run)
in the run command: 
`java -jar -Dspring.config.location=classpath:config/application.yml,/path/to/config.yml transmart-proxy-server/target/transmart-variant-store-connector-<version>.jar`
-> path to jar should start with `transmart-variant-store-connector/target/...`

Same in [Run in development mode](https://github.com/thehyve/transmart-variant-store-connector#run-in-development-mode) part:
`cd transmart-proxy-server` -> `cd transmart-variant-store-connector`

**Comment by gijskant** [comment]
Instructions updated in #1.
